# Generated by Django 4.2.6 on 2023-12-14 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(max_length=255, verbose_name='Область работы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('rbm', 'РБМ'), ('rp', 'РП')], max_length=250, verbose_name='Роль участника')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='VisitToTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.CharField(max_length=255, verbose_name='Визитов (ТТ)')),
                ('retail', models.CharField(max_length=255, verbose_name='Розничных ТТ')),
                ('sto', models.CharField(max_length=255, verbose_name='СТО')),
                ('retail_buy_SAKURA_and_have', models.CharField(max_length=255, verbose_name='Закупают SAKURA и есть в наличии')),
                ('sto_buy_SAKURA_and_have', models.CharField(max_length=255, verbose_name='Закупают SAKURA и есть в наличии')),
                ('sto_dont_buy_SAKURA_and_have', models.CharField(max_length=255, verbose_name='СТО Не закупают SAKURA или только под заказ в %')),
                ('retail_dont_buy_SAKURA_and_have', models.CharField(max_length=255, verbose_name='Розничные ТТ Не закупают SAKURA или только под заказ в %')),
                ('month', models.DateField(verbose_name='За какой месяц?')),
                ('user_profile', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.userprofile')),
            ],
            options={
                'verbose_name': 'Посещение ТТ:',
                'verbose_name_plural': 'Посещение ТТ:',
            },
        ),
        migrations.CreateModel(
            name='TextSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок листа')),
                ('text', models.TextField(verbose_name='Текстовое поле')),
                ('text_image', models.ImageField(blank=True, null=True, upload_to='text_image/')),
                ('user_profile', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.userprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.visittott', verbose_name='Посещение ТТ:')),
            ],
            options={
                'verbose_name': 'Текстовый Слайдер',
                'verbose_name_plural': 'Текстовые Слайдеры',
            },
        ),
    ]
