# Generated by Django 4.2.6 on 2023-11-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageslide',
            options={'verbose_name': 'Image Слайдер', 'verbose_name_plural': 'Image Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='textslide',
            options={'verbose_name': 'Текстовый Слайдер', 'verbose_name_plural': 'Текстовые Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='visittott',
            options={'verbose_name': 'Посещение ТТ:', 'verbose_name_plural': 'Посещение ТТ:'},
        ),
    ]
