# Generated by Django 4.2.6 on 2023-12-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_userprofile_rbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textslide',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_slides', to='app2.visittott', verbose_name='Посещение ТТ:'),
        ),
    ]
