# Generated by Django 4.2.6 on 2023-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_imageslide_options_alter_textslide_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workplace',
            field=models.CharField(max_length=255, verbose_name='Область работы'),
        ),
    ]
