# Generated by Django 4.2.6 on 2023-11-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_visittott_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittott',
            name='user_profile',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='app2.userprofile'),
        ),
    ]
