# Generated by Django 4.2.6 on 2023-11-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_visittott_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageslide',
            name='user_profile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.userprofile'),
        ),
        migrations.AddField(
            model_name='textslide',
            name='user_profile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.userprofile'),
        ),
        migrations.AlterField(
            model_name='visittott',
            name='user_profile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.userprofile'),
        ),
    ]
