# Generated by Django 4.2.6 on 2023-11-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_alter_textslide_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslide',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.visittott', verbose_name='Посещение ТТ:'),
        ),
        migrations.AlterField(
            model_name='textslide',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.visittott', verbose_name='Посещение ТТ:'),
        ),
    ]
