# Generated by Django 4.2.6 on 2023-11-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_alter_imageslide_visit_alter_textslide_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
