version: '3.7'

services:
  web:
    build: .
    command:  sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn RP_project.wsgi:application --bind 0.0.0.0:30063 --timeout 600 --reload -w 4"
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/static
    ports:
      - "30063:30063"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rp_admin
      - POSTGRES_PASSWORD=haeryrdfghdfg
      - POSTGRES_DB=rp_admin
    ports:
      - "5431:5431"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "124:124"
      - "441:441"
    depends_on:
      - web
    volumes:
      - ./nginx/cert:/etc/ssl/cert
      - static_volume:/usr/src/app/static
volumes:
  postgres_data:
  static_volume:
